// react/src/components/block.tsx
import { SxProps } from "@mui/material"
import Box from "@mui/material/Box"

interface BlockProps {
    sx?: SxProps,
    height?: number
    width?: number,
    children: React.ReactNode,
    icon: React.ReactNode
}

export default function Block({ sx, height, width, children, icon } : BlockProps) {
    return (
        <Box
            sx={{
                position: 'relative',
                bgcolor: '#00000055',
                borderTopLeftRadius: 20,
                borderBottomRightRadius: 20,
                p: 2,
                mx: '10px',
                height: height ?? 180,
                width: width ?? 200,
                color: 'text.primary',
                ...sx
            }}
        >
            <Box
                sx={{
                    position: 'absolute',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',   
                    top: -10,
                    right: -10,
                    height: 40,
                    width: 40,
                    background: 'linear-gradient(0deg,#400000,maroon)',
                    borderRadius: 2,
                    textAlign: 'center'
                }}
            >
                {icon}
            </Box>
            {children}
        </Box>   
    )
}

// client/src/components/Block.vue
<template>
  <v-card elevation="6" shaped class="block ma-3">
    <div class="title rounded text-center">
      <v-icon>{{ icon }}</v-icon>
    </div>
    <slot></slot>
  </v-card>
</template>

<script>
export default {
  name: 'Block',
  props: {
    icon: String
  }
}
</script>

<style scoped>
  .block {
    /* position: relative; */
    /* background: #ffffff20; */
    width: 12em;
    height: 12em;
  }
  .title {
    display: inline-block;
    position: absolute;
    top: -0.5em;
    right: -0.5em;
    width: 2em;
    height: 2em;
    /* line-height: 2.5em; */
    color: white;
    font-size: 1.5em;
    background: linear-gradient(to top, #400000, #800000);
  }
</style>
